### PR TITLE
Added iTerm2 theme

### PR DESCRIPTION
**Pull request by LokeCarlsson**

### CODE REVIEW

**Comment by ntwigs** [comment]
@LokeCarlsson Would love to have a screenshot of iTerm with the theme in the readme! :rocket:

**Comment by LokeCarlsson** [comment]
skarmavbild 2018-02-23 kl 13 07 56

**Comment by LokeCarlsson** [comment]
skarmavbild 2018-02-23 kl 13 06 16

**Comment by ntwigs** [comment]
@LokeCarlsson .. to the **README** :wink: :rocket:

**Comment by LokeCarlsson** [comment]
@ntwigs Done!

**Pull request merged**
